---
name: "SubSync"
guid: "D17B7DA2-F00F-4073-8E2D-F05F8AF6CEB8"
version: "0.1.0.2"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "Synchronize subtitles with SubSync"
description: "This plugin integrates with SubSync to synchronize subtitles with media files."
category: "Metadata"
owner: "theshoeshiner"
artifacts:
- "Jellyfin.Plugin.SubSync.dll"
changelog: "https://github.com/theshoeshiner/jellyfin-plugin-subsync/raw/main/CHANGELOG.md"
